### ISSUE TITLE
哥们  我这里有vue3.0 ts的前端项目 有兴趣兼职吗或者实习吗

### ISSUE THREAD

**Issue by JockJo** [guodonglw/vue3.0-admin#2]

**Comment by JockJo** [comment]
感兴趣，欢迎发送简历到hualahualatech@163.com

**Comment by guodonglw** [comment]
哈哈哈，目前没有兴趣，感谢关注😄

**Comment by guodonglw** [comment]
> 感兴趣，欢迎发送简历到[hualahualatech@163.com](mailto:hualahualatech@163.com)

哈哈哈，目前没有兴趣，感谢关注😄
