### ISSUE TITLE
你确实是vue3.0？？？你是哪家培训？这么坑人？

### ISSUE THREAD

**Issue by Alarikshaw** [guodonglw/vue3.0-admin#6]

**Comment by guodonglw** [comment]
xd，不是培训的哦，是个人开发者，如果确实需要vue3的项目，请移步https://github.com/guodonglw/vue3.0-admin。这个项目应该算是vue2中最符合vue3的理念的项目了，包括聚合api，ts的支持都不错，一般培训机构是做不到的，至于叫vue3，更多的是为了吸引眼球吧，这个项目初建的时候，vue3还是个概念，希望不要纠结于具体的vue版本，而更多的关注到代码。

**Comment by Alarikshaw** [comment]
得了得了，少忽悠人了。什么移步？是就是，不是就不是。
你但凡看过写过vue3，就应该知道2和3的区别有多大。
还有，版本不同就是不同，什么叫最符合？
一般的培训机构做不到，意思是你这家培训机构做的到？我都不想给别人打广告，井底之蛙，去看看人家培训机构做的，好吗？你哪怕把别人的代码拿过来换个壳子也行啊？
吸引眼球，我倒是佩服你，直接就说出来了。最后一句话，真的可笑至极，就因为代码不同，才分的版本。
